meta:
  name: Fizzy
  url: ""
  description: 生活与思考
  icon: /favicon.ico
  footerInfo: 生活与思考
post:
  showFeatureImage: true
  featureText: 推荐
seo:
  title: Fizzy
  keywords: jamstack, Hobby
appearance:
  mainColor: "#538fcd"
  linkHoverColor: "#538fcd"
component:
  authorBox: true
  codeLineNumbers: true
