meta:
  name: 见时随笔
  url: ""
  description: 生活与思考
  icon: /static/img/tree.png
  footerInfo: 生活与思考
post:
  showFeatureImage: true
  featureText: 推荐
seo:
  title: 见时随笔
  keywords: jamstack, Hobby
component:
  authorBox: true
  codeLineNumbers: true
